import Foundation

/// COCO dataset class labels mapped to Korean
enum KoreanLabels {
    static let map: [String: String] = [
        "person": "사람",
        "bicycle": "자전거",
        "car": "자동차",
        "motorcycle": "오토바이",
        "airplane": "비행기",
        "bus": "버스",
        "train": "기차",
        "truck": "트럭",
        "boat": "보트",
        "traffic light": "신호등",
        "fire hydrant": "소화전",
        "stop sign": "정지표지판",
        "parking meter": "주차미터기",
        "bench": "벤치",
        "bird": "새",
        "cat": "고양이",
        "dog": "강아지",
        "horse": "말",
        "sheep": "양",
        "cow": "소",
        "elephant": "코끼리",
        "bear": "곰",
        "zebra": "얼룩말",
        "giraffe": "기린",
        "backpack": "배낭",
        "umbrella": "우산",
        "handbag": "핸드백",
        "tie": "넥타이",
        "suitcase": "여행가방",
        "frisbee": "프리스비",
        "skis": "스키",
        "snowboard": "스노보드",
        "sports ball": "공",
        "kite": "연",
        "baseball bat": "야구배트",
        "baseball glove": "야구글러브",
        "skateboard": "스케이트보드",
        "surfboard": "서핑보드",
        "tennis racket": "테니스라켓",
        "bottle": "병",
        "wine glass": "와인잔",
        "cup": "컵",
        "fork": "포크",
        "knife": "나이프",
        "spoon": "숟가락",
        "bowl": "그릇",
        "banana": "바나나",
        "apple": "사과",
        "sandwich": "샌드위치",
        "orange": "오렌지",
        "broccoli": "브로콜리",
        "carrot": "당근",
        "hot dog": "핫도그",
        "pizza": "피자",
        "donut": "도넛",
        "cake": "케이크",
        "chair": "의자",
        "couch": "소파",
        "potted plant": "화분",
        "bed": "침대",
        "dining table": "식탁",
        "toilet": "변기",
        "tv": "TV",
        "laptop": "노트북",
        "mouse": "마우스",
        "remote": "리모컨",
        "keyboard": "키보드",
        "cell phone": "핸드폰",
        "microwave": "전자레인지",
        "oven": "오븐",
        "toaster": "토스터",
        "sink": "싱크대",
        "refrigerator": "냉장고",
        "book": "책",
        "clock": "시계",
        "vase": "꽃병",
        "scissors": "가위",
        "teddy bear": "인형",
        "hair drier": "드라이어",
        "toothbrush": "칫솔",
    ]

    static func korean(for label: String) -> String {
        map[label.lowercased()] ?? label
    }
}
